---
layout: plain
---

<div class="jumbotron">
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">

<p>Frequentist statistical inference meets<br />
Bayesian Markov-chain Monte Carlo (MCMC) methods.</p>
<h1 class="title">Happy Cloding!</h1>
<!-- <p><a class="btn btn-primary" href="{{ site.baseurl }}/dc.html">Learn more</a></p> -->
<h3>
<a href="https://twitter.com/datacloning"><i class="fa fa-twitter-square text-grey"></i></a>
<a href="https://github.com/datacloning/"><i class="fa fa-github-square text-grey"></i></a> 
<a href="http://datacloning.org/feed.xml"><i class="fa fa-rss-square text-grey"></i></a>
</h3>

            </div>
        </div>
    </div>
</div>

<div class="section-tout">
    <div class="container">
        <div class="row">

<div class="col-lg-4 col-sm-6">
<h3><i class="fa fa-laptop"></i> Easy to Install</h3>
<p>The <a href="http://cran.r-project.org/package=dclone">dclone</a> <a href="http://www.r-project.org">R</a> package
works with all major MCMC engines. See the <a href="{{ site.baseurl }}/install.html">installation guide</a>.</p>
</div>

<div class="col-lg-4 col-sm-6">
<h3><i class="fa fa-code"></i> Open Source</h3>
<p>R packages released under <a href="http://www.gnu.org/licenses/licenses.en.html">public licenses</a>, stable version on <a href="http://cran.r-project.org/package=dclone">CRAN</a>, development on <a href="https://github.com/datacloning/dclone">GitHub</a>.</p>
</div>

<div class="col-lg-4 col-sm-6">
<h3><i class="fa fa-flash"></i> High Performance</h3>
<p>Built with support for <a href="{{ site.baseurl }}/usage.html#high-performance-computing">parallel computations</a> using clusters or forking.</p>
</div>

<div class="col-lg-4 col-sm-6">
<h3><i class="fa fa-file-text-o"></i> Learn through Examples</h3>
<p>Find <a href="{{ site.baseurl }}/documentation.html">documentation</a>, <a href="{{ site.baseurl }}/tutorials/">tutorials</a>, and other <a href="{{ site.baseurl }}/courses/">teaching materials</a>.</p>
</div>

<div class="col-lg-4 col-sm-6">
<h3><i class="fa fa-cloud"></i> Contribute</h3>
<p>Share your own clode (dclone-ified code) <a href="https://github.com/datacloning/dcexamples">here</a>.</p>
</div>

<div class="col-lg-4 col-sm-6">
<h3><i class="fa fa-bullhorn"></i> Stay Updated</h3>
<p>Subscribe to the <a href="https://groups.google.com/forum/?fromgroups#!forum/dclone-users">dclone users mailing list</a> for general modeling discussions.</p>
</div>

        </div>
    </div>
</div>

*****************

<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">

<div class="well">
<h3><a href="https://github.com/datacloning/workshop-2023-edmonton">CalgaryR & YEGRUG Meetup: Data Cloning - Hierarchical Models Made Easy</a></h3>
<!-- <p><small>Posted on 2016&ndash;02&ndash;27</small></p> -->
<p><strong>Half-day workshop in Edmonton, WI, on April 13, 2023, with Peter Solymos and Subhash Lele</strong></p>
<p>Mixed models, also known as hierarchical models and multilevel models, is a useful class of models for applied sciences. The goal of this workshop is to give an introduction to the logic, theory, and implementation of these models to solve practical problems. The workshop will include a seminar style overview and hands on exercises including common model classes and examples that participants can extend for their own needs.</p>
</div>

        </div>
    </div>
    {% if site.ads %}
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
        {% include _ads.html %}
        </div>
    </div>
    {% endif %}
</div>

{% comment %}
<!-- Move old entries here. -->

Navbar organization

Software:
* Introduction
* Installation
* R packages
  - dclone
  - dcmle
  - dcextras
* Issues

Resources:
* Documentation
* Tutorials
* Courses
* Talks

Search

{% endcomment %}
