---
title: "Hierarchical models"
author: "Peter Solymos and Subhash Lele"
date: "July 16, 2016 &mdash; Madison, WI &mdash; NACCB Congress"
layout: course
output:
  pdf_document:
    toc: true
    toc_depth: 2
    number_sections: true
course:
  location: Madison
  year: 2016
  title: "Hierarchical Models Made Easy &mdash; July 16, 2016 &mdash; Madison, WI &mdash; NACCB Congress"
  lecture: Hierarchical models
  file: hierarchical-models
  previous: Hierarchical-Models-Made-Easy_Intro
  next: occupancy
---

We are now familiar with the basic concepts of statistical inference and the two philosophies that are commonly adopted to make the inferential statements. In this lecture, we will look at making inferential statements about realistic and hence complex ecological models. In the rest of the course, we will write the description of the model but will not discuss the philosophical aspects in detail. We will mostly use a graphical model and its JAGS version. We will provide *tools* to obtain either Bayesian or Frequentist inferential statements. We will discuss pros and cons of these inferential statements. The choice of the inferential statement will be left to the scientist. 

We start with *simulation* so that we can compare the results to the true
parameter values (which is never the case with real data).
Then we show the *Bayesian implementation*, and how to modify that
for *data cloning based frequentis inference*. We also showcase
peculiar properties of these model classes to highlight
similarities and differences of the different approaches,
and to demonstrate the potential pitfalls and how to avoid them.

## Models

* [Occupancy models with detection error](./occupancy.html)
* [Abundance models with detection error](./abundance.html)
* [Linear mixed-effects models (LMM)](./lmm.html)
* [Generalized linear mixed-effects models (GLMM)](./glmm.html)

