---
title: 'Hierarchical models for conservation biologists made easy'
layout: default
---

**One-day short course at [NACCB congress](http://www.scbnacongress.org/) in Madison, WI, on July 16th, with Peter Solymos and Subhash Lele.**

> We aim this training course towards conservation professionals who need to understand and feel comfortable with modern statistical and computational tools used to address conservation issues. Conservation science needs to be transparent and credible to be able to make an impact and translate information and knowledge into action.

### Where, when?

The congress program is out (see [here](http://www.xcdsystem.com/scbna/program/)).

Congress registration is <del>now open [here](http://www.scbnacongress.org/short-courses)</del> closed.

* The short course date: Saturday, July 16,
* time: 9:00 AM &ndash; 5:00 PM,
* location: Hall of Ideas H, [Monona Terrace Community and Convention Center](http://www.mononaterrace.com/).

### Description

Communicating scientific methods and results require a full understanding of concepts, assumptions and implications. However, most ecological data used in conservation decision making are inherently noisy, both due to intrinsic stochasticity found in nature and extrinsic factors of the observation processes. We are often faced with the need to combine multiple studies across different spatial and temporal resolutions. Natural processes are often hierarchical. Missing data, measurement error, soft data provided by expert opinion need to be accommodated during the analysis. Data are often limited (rare species, emerging threats), thus small sample corrections are important for properly quantify uncertainty.

Hierarchical models are useful in such situations. Fitting these models to data, however, is difficult. Advances in the last couple of decades in statistical theory and software development have fortunately made the data analysis easier, although not trivial. In this course, we propose to introduce statistical and computational tools for the analysis of hierarchical models (including tools for small sample inference) specifically in the context of conservation issues.

We will teach both Bayesian and Likelihood based approaches to these models using freely available software developed by the tutors. By presenting both Bayesian and Likelihood based approaches participants will be able to go beyond the rhetorics of philosophy of statistics and use the tools with full understanding of their assumptions and implications. This will help ensure that when they use the statistical techniques, be they Bayesian or Frequentist, they will be able to explain and communicate the results to the managers and general public appropriately.

### Organizational structure

* Introduction and overview of statistical concepts: seminar format (1&ndash;1.5 hours), followed by a short break.
* Hierarchical models: hands on training.
* Lunch break (lunch provided) with informal discussions.
* Analyzing data with temporal and spatial dependence, model identifiability: hands on training with short break in the middle.

Participants should bring their own laptops. Open source and free software, and electronic course material will be provided by organizers.

Morning coffee, and afternoon iced tea and lemonade, plus light snack of chips and salsa will be provided.

### Course resources

Each link leads to a page where it is possible to review the html
version, or view/download the source (R markdown) and the final PDF
that came out after running the models.

* [What to do before the course]({{ site.baseurl }}/courses/2016/madison/how-to-prepare.html)
* [Introduction]({{ site.baseurl }}/courses/2016/madison/Hierarchical-Models-Made-Easy_Intro.html) ([slides]({{ site.baseurl }}/courses/2016/madison/Fundamental_concepts.pdf))
* [Hierarchical models]({{ site.baseurl }}/courses/2016/madison/hierarchical-models.html):
  - [Occupancy models]({{ site.baseurl }}/courses/2016/madison/occupancy.html)
  - [Abundance models]({{ site.baseurl }}/courses/2016/madison/abundance.html)
  - [Linear mixed-effects models]({{ site.baseurl }}/courses/2016/madison/lmm.html)
  - [Generalized linear mixed-effects models]({{ site.baseurl }}/courses/2016/madison/glmm.html)
* Models with dependence:
  - [Temporal dependence]({{ site.baseurl }}/courses/2016/madison/pva.html) ([slides]({{ site.baseurl }}/courses/2016/madison/Dependent_data_analysis.pdf))
  - [Spatial dependence]({{ site.baseurl }}/courses/2016/madison/spatial.html)
* Philosophical issues with inferential paradigms ([slides]({{ site.baseurl }}/courses/2016/madison/issues.pdf))

All the code and PDF files can be downloaded as a single 
[zip archive]({{ site.baseurl }}/courses/2016/madison/madison.zip).

### Contact the organizers

* [Péter Sólymos](http://peter.solymos.org)
* [Subhash R. Lele](http://www.stat.ualberta.ca/~slele/)

### Suggested reading

Lele, S. R. and K. L. Allen, 2006.
On using expert opinion in ecological analyses: a frequentist approach. 
Environmetrics, 17:683--704. [[PDF](http://www.stat.ualberta.ca/~slele/publications/LeleAllen06.pdf)]

Lele, S. R. 2015. 
Is non-informative Bayesian analysis appropriate for wildlife management: 
survival of San Joaquin Kit Fox and declines in amphibian populations.
arXiv:1502.00483 [[PDF](http://arxiv.org/pdf/1502.00483v1.pdf)]

Lele, S.R., B. Dennis and F. Lutscher, 2007. Data cloning: easy maximum likelihood estimation for complex ecological models using Bayesian Markov chain Monte Carlo methods. Ecology Letters 10:551--563. [[PDF](http://www.math.ualberta.ca/~slele/publications/Lele%20Dennis%20Lutscher%20data%20cloning%20Ecology%20Letters%2020071.pdf)]

Lele S. R. and B. Dennis, 2009. 
Bayesian method for hierarchical models: Are ecologists making a Faustian bargain? 
Ecological Applications 19:581--584. [[PDF](http://www.stat.ualberta.ca/~slele/publications/Lele%20Dennis%2009.pdf)]

Solymos P., 2010. dclone: Data Cloning in R. The R Journal 2(2):29--37.
[[PDF](http://journal.r-project.org/archive/2010-2/RJournal_2010-2_Solymos.pdf)]

Solymos, P., Lele, S. R. and Bayne, E., 2012. 
Conditional likelihood approach for analyzing single visit abundance survey data in the presence of zero inflation and detection error. 
Environmetrics 23:197--205. [[PDF](https://drive.google.com/open?id=0B-q59n6LIwYPOTNqaWZnSlNYZWc)]

