---
title: "About the course"
author: "Peter Solymos and Subhash Lele"
output: pdf_document
layout: course
course:
  location: Montpellier
  year: 2015
  title: "Hierarchical Models Made Easy &mdash; August 1, 2015 &mdash; Montpellier, France &mdash; ICCB/ECCB Congress"
  lecture: About
  file: about-the-course
  previous: index
  next: how-to-prepare
---

### Goal and justification

We aim this training course towards the conservation professionals who need to understand and feel comfortable with modern statistical and computational tools used to address pressing conservation issues.

Most ecological data used in conservation decision making are inherently noisy, both due to the intrinsic stochasticity found in nature and the extrinsic factors of the observation processes. We are often faced with the need to combine multiple studies across different spatial and temporal resolutions. Natural processes are often hierarchical; one process affecting the next and so on. Missing data, measurement error, soft data provided by the expert opinion need to be accommodated during the statistical analysis. 

Hierarchical models or random effects models is a natural class of models that are useful in such situations. Fitting these models to data, however, is difficult. Advances in the last couple of decades in statistical theory and software development have fortunately made the data analysis easier, although not trivial. In this workshop, we propose to introduce statistical and computational tools for the analysis of hierarchical models specifically in the context of conservation issues. We will teach both Bayesian and Likelihood based approaches to these models using freely available software developed by the tutors. By presenting both Bayesian and Likelihood based approaches, the participants will be able to go beyond the rhetorics of philosophy of statistics and use the tools with full understanding of their assumptions and implications.

Active learning is the best way to learn statistical analysis and we will be promoting it in the session. Participants will be asked to take part in the analysis: first hand analytics experience from start to finish. We will use examples that are relevant to conservation biology. Types of models discussed include population dynamics models in space and time used in Population Viability Analysis, monitoring designs for occupancy and abundance data, dynamical systems models, and capture-recapture sampling. 

In this course, we will not only demystify the statistical thinking but also, and more importantly from the practical point of view, we will teach the use of a freely available statistical package ‘dclone’. It is a freely available software package based on R, JAGS and BUGS. The expected outcome of the course is a solid foundation for further professional development via increased confidence in using hierarchical models in a conservation context.

### Organizational structure

* Format: The introduction and overview is in seminar format (1-1.5 hours), the rest of the course is in workshop format with two breaks, the third part after the second break is possibly centered around participant’s own projects.
* Duration: 6-8 hours of instruction time with 2 x 30 minutes breaks (9:00-12:00, 12:30-15:30, 16:00-18:00)
* Expected number of participants: minimum 12, maximum 25.
* Equipment necessary: Participants should bring their own laptops. Organizers should arrange for projector, electric outlets and power cords for plugging in computers. Open source and free software, and electronic course material will be provided by tutors. Internet access is necessary but tutors will provide software/code/course material on DVD or USB sticks in case of offline format.

### Contact the organizers

* [Péter Sólymos](http://peter.solymos.org)
* [Subhash R. Lele](http://www.stat.ualberta.ca/~slele/)

